version: 0.2
phases:
  build:
    commands:
      - printf '{"ImageURI":"937448338924.dkr.ecr.ap-southeast-2.amazonaws.com/alpine:latest"}' > imageDetail.json
  artifacts:
    files:
      - imageDetail.json
